name: Build NetHunter Kernel
on:
  workflow_dispatch: # Allows you to start the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex git libelf-dev libssl-dev libncurses-dev python3

      - name: Execute Build Script
        run: |
          cd kali-nethunter-kernel-builder
          cp ../nh_files/local.config .
          chmod +x build.sh
          ./build.sh

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: Nethunter-Kernel-beyond2lte
          path: kali-nethunter-kernel-builder/out/*.zip
